export const APP_ROUTES = {
  dashboard: "/dashboard",
  dashboardContributionMargin: "/dashboard/contribution-margin",
  dre: "/dre",
  sales: "/sales",
  productInsights: "/product-insights",
  productInsightsExecutive: "/product-insights/visao-executiva",
  productInsightsRadar: "/product-insights/radar",
  productInsightsDetail: "/product-insights/detalhamento",
  media: "/media",
  mediaExecutive: "/media/visao-executiva",
  mediaRadar: "/media/radar",
  mediaCampaigns: "/media/campanhas",
  mediaAds: "/media/anuncios",
  traffic: "/traffic",
  costCenter: "/cost-center",
  cmv: "/cmv",
  feed: "/feed",
  creativeOps: "/creative-ops",
  import: "/import",
  sanitization: "/sanitization",
  settings: "/settings",
  settingsGovernance: "/settings#platform-governance",
  settingsAutomation: "/settings#integration-automation",
  integrations: "/integrations",
  integrationsTutorials: "/integrations/tutorials",
  integrationsTutorialMeta: "/integrations/tutorials/meta",
  integrationsTutorialGa4: "/integrations/tutorials/ga4",
  adminStores: "/admin/stores",
  help: "/help",
} as const;

export type AppRoute = (typeof APP_ROUTES)[keyof typeof APP_ROUTES];
